name: Fetch Stoic Quote and Update README

on:
  schedule:
    - cron: '0 0 * * *'
   
jobs:
  fetch-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Stoic Quote
        id: fetch-quote
        run: |
          # Use a curl or wget command to fetch the Stoic quote JSON from the API.
          # Replace the URL with the actual API endpoint.
          quote=$(curl -s https://stoicquotesapi.com/api/v1/quote/random)

          # Extract the quote and author from the JSON response.
          quote_text=$(echo "$quote" | jq -r '.text')
          quote_author=$(echo "$quote" | jq -r '.author')

          # Store the quote and author as output variables.
          echo "::set-output name=quote_text::$quote_text"
          echo "::set-output name=quote_author::$quote_author"

      - name: Update README
        run: |
          # Read the current README.md file.
          readme_content=$(cat README.md)

          # Replace a placeholder in the README with the fetched quote.
          new_readme_content="${readme_content//<!-- STOIC_QUOTE -->/<p>\"${{ steps.fetch-quote.outputs.quote_text }}\" - ${{ steps.fetch-quote.outputs.quote_author }}</p>}"

          # Overwrite the README.md file with the updated content.
          echo "$new_readme_content" > README.md

        # Commit and push the changes back to the repository.
        - name: Commit and Push Changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "Update README with a new Stoic quote"
            git push
