name: Fetch Stoic Quote and Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule it to run every day at 10 AM (UTC)

jobs:
  fetch-quote:
    permissions: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Stoic Quote
        id: fetch-quote
        run: |
          # Use a curl or wget command to fetch the Stoic quote JSON from the API.
          # Replace the URL with the actual API endpoint.
          quote=$(curl -s https://stoic-quotes.com/api/quote)

          # Extract the quote and author from the JSON response.
          quote_text=$(echo "$quote" | jq -r '.text')
          quote_author=$(echo "$quote" | jq -r '.author')

          # Store the quote and author as output variables.
          echo "::set-output name=quote_text::$quote_text"
          echo "::set-output name=quote_author::$quote_author"

      - name: Update README with Stoic Quote
        run: |
          # Fetch the Stoic quote and author as before
          quote_text="${{ steps.fetch-quote.outputs.quote_text }}"
          quote_author="${{ steps.fetch-quote.outputs.quote_author }}"

          # Create the HTML code for the new quote
          new_quote_html="<p>\"${quote_text}\" - ${quote_author}</p>"

          # Use sed to replace the previous Stoic quote section
          sed -i -e "/<!-- STOIC_QUOTE -->/,/<!-- STOIC_QUOTE_END -->/c\<!-- STOIC_QUOTE -->\n${new_quote_html}\n<!-- STOIC_QUOTE_END -->" README.md

          # Commit and push the changes back to the repository
          git config --local user.email "cyrilp.perso@gmail.com"
          git config --local user.name "CyrilPerrinjaquet"
          git add README.md
          git commit -m "Update README with a new Stoic quote"
          git push
